### ISSUE TITLE
Add another client access example on exercise 5 for Maps

### ISSUE THREAD

**Issue by doublebyte1** [geopython/diving-into-pygeoapi#117]
@krishnaglodha currently we only have OWSLib as an example [here](https://dive.pygeoapi.io/publishing/ogcapi-maps/). Add another example of client access using a different tool/library.

Some examples of client implementations can be found here:
https://github.com/opengeospatial/ogcapi-maps/blob/master/implementations.adoc#clients

**Comment by krishnaglodha** [comment]
I tried with https://gitlab.com/IvanSanchez/leaflet.imageoverlay.ogcapi 
In theory it works 

https://github.com/geopython/diving-into-pygeoapi/assets/47075664/ba601cbf-292c-4edd-a194-3e19f3a6bcef


but the issue is that the points are not places correctly, I'm not sure if it is error from leaflet.OGCAPI extension of pygeoapi. But the data only starts being at correct location when we are super zoomed. 
Also as per the doc of leaflet extension https://gitlab.com/IvanSanchez/leaflet.imageoverlay.ogcapi#caveats , I have reprojected data to `EPSG:3857` and then trying to use it

**Comment by doublebyte1** [comment]
This looks like a projection issue. Did you try it with another dataset from mapserver, to see if it still holds?

**Comment by krishnaglodha** [comment]
https://github.com/geopython/diving-into-pygeoapi/pull/118
